'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsSorianaProduccion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.sci-grupo.com.mx/", ConfigurationName:="wsSorianaProduccion.wseDocReciboSoap")>  _
    Public Interface wseDocReciboSoap
        
        'CODEGEN: Generating message contract since element name XMLCFD from namespace http://www.sci-grupo.com.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.sci-grupo.com.mx/RecibeCFD", ReplyAction:="*")>  _
        Function RecibeCFD(ByVal request As wsSorianaProduccion.RecibeCFDRequest) As wsSorianaProduccion.RecibeCFDResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibeCFDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecibeCFD", [Namespace]:="http://www.sci-grupo.com.mx/", Order:=0)>  _
        Public Body As wsSorianaProduccion.RecibeCFDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsSorianaProduccion.RecibeCFDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sci-grupo.com.mx/")>  _
    Partial Public Class RecibeCFDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public XMLCFD As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal XMLCFD As String)
            MyBase.New
            Me.XMLCFD = XMLCFD
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecibeCFDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecibeCFDResponse", [Namespace]:="http://www.sci-grupo.com.mx/", Order:=0)>  _
        Public Body As wsSorianaProduccion.RecibeCFDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsSorianaProduccion.RecibeCFDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sci-grupo.com.mx/")>  _
    Partial Public Class RecibeCFDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RecibeCFDResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RecibeCFDResult As String)
            MyBase.New
            Me.RecibeCFDResult = RecibeCFDResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wseDocReciboSoapChannel
        Inherits wsSorianaProduccion.wseDocReciboSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wseDocReciboSoapClient
        Inherits System.ServiceModel.ClientBase(Of wsSorianaProduccion.wseDocReciboSoap)
        Implements wsSorianaProduccion.wseDocReciboSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsSorianaProduccion_wseDocReciboSoap_RecibeCFD(ByVal request As wsSorianaProduccion.RecibeCFDRequest) As wsSorianaProduccion.RecibeCFDResponse Implements wsSorianaProduccion.wseDocReciboSoap.RecibeCFD
            Return MyBase.Channel.RecibeCFD(request)
        End Function
        
        Public Function RecibeCFD(ByVal XMLCFD As String) As String
            Dim inValue As wsSorianaProduccion.RecibeCFDRequest = New wsSorianaProduccion.RecibeCFDRequest()
            inValue.Body = New wsSorianaProduccion.RecibeCFDRequestBody()
            inValue.Body.XMLCFD = XMLCFD
            Dim retVal As wsSorianaProduccion.RecibeCFDResponse = CType(Me,wsSorianaProduccion.wseDocReciboSoap).RecibeCFD(inValue)
            Return retVal.Body.RecibeCFDResult
        End Function
    End Class
End Namespace
